# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='secrets_app.User'),
        ),
    ]
