# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0002_secret_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
