# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0005_secret_likers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='secret',
            name='like',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
