# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0006_auto_20170527_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='likers',
        ),
        migrations.AddField(
            model_name='secret',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
