# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0007_auto_20170527_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='secret',
            name='like_count',
        ),
        migrations.AddField(
            model_name='like',
            name='secret_like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secrets_app.Secret'),
        ),
        migrations.AddField(
            model_name='like',
            name='user_like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secrets_app.User'),
        ),
    ]
