# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0008_auto_20170527_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='secret_like',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user_like',
        ),
        migrations.AddField(
            model_name='secret',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='secret',
            name='likers',
            field=models.ManyToManyField(related_name='likedsecrets', to='secrets_app.User'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
