=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end


fibonacci_numbers = [1, 2]

i = 0

while i < 30
  if (fibonacci_numbers[i].to_i + fibonacci_numbers[i+1].to_i) < 4000000
    fibonacci_numbers << (fibonacci_numbers[i].to_i + fibonacci_numbers[i+1].to_i)
    i += 1
  end
end

puts fibonacci_numbers.select {|num| num.even?}.reduce(:+)