# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inprint',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
