# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shanes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DryErase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=38)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dry_erase', to='shanes_app.Instructor')),
            ],
        ),
    ]
